on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - run: pip install -r requirements.txt pyinstaller
      - run: pyinstaller keylogger.spec
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}
          path: dist/*
